# Generated by Django 5.2.7 on 2025-10-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="university_logos/")),
                ("rating", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
