# Generated by Django 6.0.2 on 2026-03-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_review_author_name_review_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="rating",
            field=models.FloatField(default=0.0, verbose_name="Рейтинг"),
        ),
    ]
