# Generated by Django 6.0.2 on 2026-03-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_review_unique_review_per_user_per_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="universities/",
                verbose_name="Изображение",
            ),
        ),
    ]
