# Generated by Django 6.0.2 on 2026-03-25 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_faculty_teacher_facultyreview_teacherreview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Код специальности"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("rating", models.FloatField(default=0.0, verbose_name="Рейтинг")),
            ],
            options={
                "verbose_name": "Специальность",
                "verbose_name_plural": "Специальности",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SpecialtyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Ужасно"),
                            (2, "2 - Плохо"),
                            (3, "3 - Нормально"),
                            (4, "4 - Хорошо"),
                            (5, "5 - Отлично"),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата отзыва"),
                ),
                (
                    "moderated",
                    models.BooleanField(default=False, verbose_name="Прошел модерацию"),
                ),
            ],
            options={
                "verbose_name": "Отзыв на специальность",
                "verbose_name_plural": "Отзывы на специальности",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="facultyreview",
            name="unique_faculty_review_per_user",
        ),
        migrations.AddField(
            model_name="specialty",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specialties",
                to="main.faculty",
                verbose_name="Факультет (опционально)",
            ),
        ),
        migrations.AddField(
            model_name="specialty",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialties",
                to="main.university",
                verbose_name="Университет",
            ),
        ),
        migrations.AddField(
            model_name="specialtyreview",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialty_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="specialtyreview",
            name="specialty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialty_reviews",
                to="main.specialty",
                verbose_name="Специальность",
            ),
        ),
        migrations.RemoveField(
            model_name="facultyreview",
            name="author",
        ),
        migrations.RemoveField(
            model_name="facultyreview",
            name="faculty",
        ),
        migrations.AddConstraint(
            model_name="specialtyreview",
            constraint=models.UniqueConstraint(
                fields=("author", "specialty"), name="unique_specialty_review_per_user"
            ),
        ),
        migrations.DeleteModel(
            name="FacultyReview",
        ),
    ]
