# Generated by Django 6.0.2 on 2026-03-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_specialty_specialtyreview_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialty",
            name="university",
        ),
        migrations.AddField(
            model_name="specialty",
            name="universities",
            field=models.ManyToManyField(
                blank=True, related_name="specialties", to="main.university"
            ),
        ),
    ]
